### ISSUE TITLE
Is this package part of laravel core now?

### ISSUE THREAD

**Issue by codeitlikemiley** [reinink/advanced-eloquent#3]

**Comment by reinink** [comment]
Yes and no. Yes in that you can now do this in Laravel without this package ([see here](https://laravel-news.com/eloquent-subquery-enhancements)). No in that the API is not exactly the same. Instead of using separate subquery methods, you can now add subqueries using the existing `select()` and `addSelect()` methods. It's actually a really nice API! 👌
