### ISSUE TITLE
[Question] Why did you remove the link of this package in your article

### ISSUE THREAD

**Issue by ajcastro** [reinink/advanced-eloquent#5]
First of all, I would like to thank you for this great package and article! 😃 

Is there a reason why this package is not mentioned anymore in your article?
The macro is also not mentioned anymore in the article.

https://reinink.ca/articles/dynamic-relationships-in-laravel-using-subqueries

**Comment by reinink** [comment]
Great question @ajcastro! The reason why is because since Laravel 6.0, you can do most of what this package offers directly in Laravel! See my blog post on Laravel News [here](https://laravel-news.com/eloquent-subquery-enhancements). I basically took these ideas, and added them to the Laravel core. 👌 

I suspect I'll archive this project soon, since it's no longer really needed.
